"""add tkt table

Revision ID: 20cf63fb930a
Revises: b8688a730fe6
Create Date: 2025-05-24 02:24:00.685696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20cf63fb930a'
down_revision: Union[str, None] = 'b8688a730fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('tkt_num', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('typ', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tkt_num')
    )
    op.create_index(op.f('ix_tickets_tkt_num'), 'tickets', ['tkt_num'], unique=False)
    op.create_index(op.f('ix_tickets_username'), 'tickets', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_username'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_tkt_num'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
