"""create users table

Revision ID: f8579e5f59c0
Revises: 20cf63fb930a
Create Date: 2025-05-24 02:28:37.667378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8579e5f59c0'
down_revision: Union[str, None] = '20cf63fb930a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_username', table_name='tickets')
    op.create_index(op.f('ix_tickets_username'), 'tickets', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_username'), table_name='tickets')
    op.create_index('ix_tickets_username', 'tickets', ['username'], unique=True)
    # ### end Alembic commands ###
